### ISSUE TITLE
Very smart

### ISSUE THREAD

**Issue by mysticaltech** [gesslein/k3os-hcloud#1]
Wow, very smart way of installing k3os, any tips or tools for k3s?

**Comment by lotharbach** [comment]
Glad you like it, and that you found it in the first place. I have to do some SEO to make it easier to find with the most obvious search terms I think.

I don't have anything special to recommend for k3os/k3s, it's really compatible to standard kubernetes. I try to identify and use the most established projects, operators, manifests etc to avoid running into to much trouble.

**Comment by mysticaltech** [comment]
Appreciate that, makes sense indeed!
